= 用 Turbo Drive 导航
:description: Turbo Drive accelerates links and form submissions by negating the need for full page reloads.
:permalink: /handbook/drive.html

Turbo Drive 是 Turbo 的页面级导航增强部分。它会监控页面的链接点击和表单提交，一旦捕获会在后端执行并且进行部分页面更新。它其实是以前的 https://github.com/turbolinks/turbolinks[Turbolinks] 的一个升级。

$\{toc}

== 页面导航基础

Turbo Drive 将页面导航建模为用__操作（action）__来__访问（visit）__一个__位置（location）__（URL）。

访问代表从点击到呈现的整个导航生命周期----包括更改浏览器历史记录、发出网络请求、从缓存中恢复页面副本、呈现最终响应以及更新滚动位置。

访问有两种类型：具有 advance 或 replace 操作的 _应用访问_ 和具有 restore 操作的 _恢复访问_。

== 应用访问

应用访问通过点击启用 Turbo Drive 的链接或者通过编程调用 link:/reference/drive#turbodrivevisit[`Turbo.visit(location)`] 发起。

应用访问总是会先发起一个网络请求，当响应到达的时候，Turbo Drive 会呈现其 HTML 并完成访问。

如果可能，Turbo Drive 会在访问开始后立即从缓存中呈现页面预览。这会明显提高访问高频导航的相同页面的感知速度。

如果访问的位置包含锚点，Turbo Drive 将尝试滚动到锚定元素。否则，它将滚动到页面顶部。

应用访问会导致浏览器历史记录发生变化；访问的 _操作_ 决定了访问方式。

image::https://s3.amazonaws.com/turbolinks-docs/images/advance.svg[advance 访问操作]

默认的访问操作是 _advance_。在 advance 操作期间，Turbo Drive 用 https://developer.mozilla.org/en-US/docs/Web/API/History/pushState[`history.pushState`] 将新条目推送到浏览器的历史堆栈中。

使用 Turbo Drive https://github.com/hotwired/turbo-ios[iOS 适配器]的应用程序通常通过将新的视图控制器推送到导航堆栈来处理 advance 访问。类似地，使用 https://github.com/hotwired/turbo-android[Android 适配器]的应用程序通常会将新活动推送到后台堆栈。

image::https://s3.amazonaws.com/turbolinks-docs/images/replace.svg[Replace 访问操作]

您可能希望访问一个位置而不将新的历史条目推入堆栈。_replace_ 访问操作使用 https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState[`history.replaceState`] 丢弃最顶层的历史条目并将其替换为新位置。

要指定跟随链接应触发 replace 访问，请使用 `data-turbo-action="replace"` 注释链接：

[,html]
----
<a href="/edit" data-turbo-action="replace">Edit</a>
----

要以编程方式使用 replace 操作访问位置，请将 `action: "replace"` 选项传递给 `Turbo.visit`：

[,js]
----
Turbo.visit("/edit", { action: "replace" })
----

使用 Turbo Drive 的 https://github.com/hotwired/turbo-ios[iOS 适配器]的应用程序通常通过关闭最顶层的视图控制器并将新的视图控制器推送到导航堆栈上而不带动画来处理 replace 访问。

== 恢复访问

当您使用浏览器的后退或前进按钮导航时，Turbo Drive 会自动启动恢复访问。使用 https://github.com/hotwired/turbo-ios[iOS] 或 https://github.com/hotwired/turbo-android[Android] 适配器的应用程序在导航堆栈中向后移动时会启动恢复访问。

image::https://s3.amazonaws.com/turbolinks-docs/images/restore.svg[Restore visit action]

如果可能，Turbo Drive 将在不发出请求的情况下从缓存中呈现页面的副本。否则，它将通过网络检索页面的新副本。有关更多详细信息，请参阅link:/handbook/building#understanding-caching[了解缓存]。

Turbo Drive 在导航离开之前保存每个页面的滚轮位置，并在恢复访问时自动返回到此保存的位置。

恢复访问具有 _restore_ 操作，Turbo Drive 保留它们以供内部使用。您不应尝试使用 `restore` 操作来注释链接或调用 Turbo.visit。

== 早于开始的取消操作

Application visits can be canceled before they start, regardless of whether they were initiated by a link click or a call to link:/reference/drive#turbovisit[`Turbo.visit`].

Listen for the `turbo:before-visit` event to be notified when a visit is about to start, and use `event.detail.url` (or `$event.originalEvent.detail.url`, when using jQuery) to check the visit's location. Then cancel the visit by calling `event.preventDefault()`.

Restoration visits cannot be canceled and do not fire `turbo:before-visit`. Turbo Drive issues restoration visits in response to history navigation that has _already taken place_, typically via the browser's Back or Forward buttons.

== Pausing Rendering

Application can pause rendering and make additional preparation before it will be executed.

Listen for the `turbo:before-render` event to be notified when rendering is about to start, and pause it using `event.preventDefault()`. Once the preparation is done continue rendering by calling `event.detail.resume()`.

An example use case is adding exit animation for visits:

[,javascript]
----
document.addEventListener('turbo:before-render', async (event) => {
  event.preventDefault()

  await animateOut()

  event.detail.resume()
})
----

== Pausing Requests

Application can pause request and make additional preparation before it will be executed.

Listen for the `turbo:before-fetch-request` event to be notified when a request is about to start, and pause it using `event.preventDefault()`. Once the preparation is done continue request by calling `event.detail.resume()`.

An example use case is setting `Authorization` header for the request:

[,javascript]
----
document.addEventListener('turbo:before-fetch-request', async (event) => {
  event.preventDefault()

  const token = await getSessionToken(window.app)
  event.detail.fetchOptions.headers['Authorization'] = `Bearer ${token}`

  event.detail.resume()
})
----

== Performing Visits With a Different Method

By default, link clicks send a `GET` request to your server. But you can change this with `data-turbo-method`:

[,html]
----
<a href="/articles/54" data-turbo-method="delete">Delete the article</a>
----

The link will get converted into a hidden form next to the `a` element in the DOM. This means that the link can't appear inside another form, as you can't have nested forms.

You should also consider that for accessibility reasons, it's better if use actual forms and buttons for anything that's not a GET.

== Disabling Turbo Drive on Specific Links or Forms

Turbo Drive can be disabled on a per-element basis by annotating the element or any of its ancestors with `data-turbo="false"`.

[,html]
----
<a href="/" data-turbo="false">Disabled</a>

<form action="/messages" method="post" data-turbo="false">
  ...
</form>

<div data-turbo="false">
  <a href="/">Disabled</a>
  <form action="/messages" method="post">
    ...
  </form>
</div>
----

To reenable when an ancestor has opted out, use `data-turbo="true"`:

[,html]
----
<div data-turbo="false">
  <a href="/" data-turbo="true">Enabled</a>
</div>
----

Links or forms with Turbo Drive disabled will be handled normally by the browser.

If you want Drive to be opt-in rather than opt-out, then you can set `Turbo.session.drive = false`; then, `data-turbo="true"` is used to enable Drive on a per-element basis. If you're importing Turbo in a JavaScript pack, you can do this globally:

[,js]
----
import { Turbo } from "@hotwired/turbo-rails"
Turbo.session.drive = false
----

== Displaying Progress

During Turbo Drive navigation, the browser will not display its native progress indicator. Turbo Drive installs a CSS-based progress bar to provide feedback while issuing a request.

The progress bar is enabled by default. It appears automatically for any page that takes longer than 500ms to load. (You can change this delay with the link:/reference/drive#turbodrivesetprogressbardelay[`Turbo.setProgressBarDelay`] method.)

The progress bar is a `<div>` element with the class name `turbo-progress-bar`. Its default styles appear first in the document and can be overridden by rules that come later.

For example, the following CSS will result in a thick green progress bar:

[,css]
----
.turbo-progress-bar {
  height: 5px;
  background-color: green;
}
----

To disable the progress bar entirely, set its `visibility` style to `hidden`:

[,css]
----
.turbo-progress-bar {
  visibility: hidden;
}
----

== Reloading When Assets Change

Turbo Drive can track the URLs of asset elements in `<head>` from one page to the next and automatically issue a full reload if they change. This ensures that users always have the latest versions of your application's scripts and styles.

Annotate asset elements with `data-turbo-track="reload"` and include a version identifier in your asset URLs. The identifier could be a number, a last-modified timestamp, or better, a digest of the asset's contents, as in the following example.

[,html]
----
<head>
  ...
  <link rel="stylesheet" href="/application-258e88d.css" data-turbo-track="reload">
  <script src="/application-cbd3cd4.js" data-turbo-track="reload"></script>
</head>
----

== Ensuring Specific Pages Trigger a Full Reload

You can ensure visits to a certain page will always trigger a full reload by including a `<meta name="turbo-visit-control">` element in the page's `<head>`.

[,html]
----
<head>
  ...
  <meta name="turbo-visit-control" content="reload">
</head>
----

This setting may be useful as a workaround for third-party JavaScript libraries that don't interact well with Turbo Drive page changes.

== Setting a Root Location

By default, Turbo Drive only loads URLs with the same origin--i.e. the same protocol, domain name, and port--as the current document. A visit to any other URL falls back to a full page load.

In some cases, you may want to further scope Turbo Drive to a path on the same origin. For example, if your Turbo Drive application lives at `/app`, and the non-Turbo Drive help site lives at `/help`, links from the app to the help site shouldn't use Turbo Drive.

Include a `<meta name="turbo-root">` element in your pages`' `<head>` to scope Turbo Drive to a particular root location. Turbo Drive will only load same-origin URLs that are prefixed with this path.

[,html]
----
<head>
  ...
  <meta name="turbo-root" content="/app">
</head>
----

== Form Submissions

Turbo Drive handles form submissions in a manner similar to link clicks. The key difference is that form submissions can issue stateful requests using the HTTP POST method, while link clicks only ever issue stateless HTTP GET requests.

Throughout a submission, Turbo Drive will dispatch a series of link:/reference/events[events] that
target the `<form>` element and https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture[bubble up] through the document:

. `turbo:submit-start`
. `turbo:before-fetch-request`
. `turbo:before-fetch-response`
. `turbo:submit-end`

During a submission, Turbo Drive will set the "submitter" element's https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled[disabled] attribute when the submission begins, then remove the attribute after the submission ends. When submitting a `<form>` element, browser's will treat the `<input type="submit">` or `<button>` element that initiated the submission as the https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter[submitter]. To submit a `<form>` element programmatically, invoke the https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit[HTMLFormElement.requestSubmit()] method and pass an `<input type="submit">` or `<button>` element as an optional parameter.

If there are other changes you'd like to make during a `<form>` submission (for
example, disabling _all_ https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/elements[fields within a submitted `<form>`]), you
can declare your own event listeners:

[,js]
----
addEventListener("turbo:submit-start", ({ target }) => {
  for (const field of target.elements) {
    field.disabled = true
  }
})
----

== Redirecting After a Form Submission

After a stateful request from a form submission, Turbo Drive expects the server to return an https://en.wikipedia.org/wiki/HTTP_303[HTTP 303 redirect response], which it will then follow and use to navigate and update the page without reloading.

The exception to this rule is when the response is rendered with either a 4xx or 5xx status code. This allows form validation errors to be rendered by having the server respond with `422 Unprocessable Entity` and a broken server to display a "Something Went Wrong" screen on a `500 Internal Server Error`.

The reason Turbo doesn't allow regular rendering on 200 is that browsers have built-in behavior for dealing with reloads on POST visits where they present a "Are you sure you want to submit this form again?" dialogue that Turbo can't replicate. Instead, Turbo will stay on the current URL upon a form submission that tries to render, rather than change it to the form action, since a reload would then issue a GET against that action URL, which may not even exist.

== Streaming After a Form Submission

Servers may also respond to form submissions with a link:streams[Turbo Streams] message by sending the header `Content-Type: text/vnd.turbo-stream.html` followed by one or more `<turbo-stream>` elements in the response body. This lets you update multiple parts of the page without navigating.
 +
 +
